version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.12.0-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: todos
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  receiver:
    build:
      dockerfile: ./.docker/service/Dockerfile
      context: .
    ports:
      - 1500:1500
    volumes:
      - ./receiver:/usr/src/app
    restart: always
  executor:
    build:
      dockerfile: ./.docker/service/Dockerfile
      context: .
    volumes:
      - ./executor:/usr/src/app
    restart: always
  reader:
    build:
      dockerfile: ./.docker/service/Dockerfile
      context: .
    ports:
      - 1501:1501
    volumes:
      - ./reader:/usr/src/app
    restart: always
